site_name: Neurobagel Developer Documentation
site_description: Internal docs on topics relevant for developing and maintaining Neurobagel
theme:
  name: material
  features:
    - navigation.footer
  palette:
    primary: cyan
    accent: deep purple
  logo: "assets/images/logo/neurobagel_logo.png"
  favicon: "assets/images/logo/neurobagel_favicon.png"
repo_url: https://github.com/neurobagel/dev-docs

nav:
  - Home: "index.md"
  - Process & Governance:
    - "How we work": "process/How we work.md"
    - "Release process": "process/Neurobagel Release process.md"
    - "Code of Conduct": "process/Neurobagel Code of Conduct.md"
    - "Personal Access Tokens (PATs)": "process/Neurobagel PATs.md"
  - Development & Tooling:
    - "Tools overview": "dev/Tools.md"
    - "Git tricks": "dev/Git Tricks.md"
    - "Version compatibility": "dev/Version compatibility.md"
  - Frontend & UI:
    - "Query Tool": "frontend/Query Tool.md"
    - "Query Tool: Result file generation": "frontend/Query Tool Result File Generation.md"
    - "Nuxt tricks": "frontend/Nuxt Tricks.md"
    - "Vite tricks": "frontend/Vite tricks.md"
    - "CSS": "frontend/CSS.md"
    - "React": "frontend/React.md"
    - "Zustand": "frontend/Zustand.md"
  - Testing & CI:
    - "Cypress Vue testing": "testing/Cypress Vue Testing.md"
    - "Cypress snippets": "testing/Cypress Snippets.md"
    - "Cypress tasks": "testing/Cypress Tasks.md"
  - Deployment & Infrastructure:
    - "Docker": "deploy/Docker.md"
    - "Dockerized NGINX deployment": "deploy/Dockerized NGINX deployment.md"
    - "Apache Jena / Fuseki": "deploy/Apache Jena Fuseki Deployment.md"
    - "Legacy Stardog setup": "deploy/Legacy Stardog graph backend deployment instructions.md"
    - "Fabrique (vGPU notes)": "deploy/Fabrique (vGPU prep and other issues).md"
    - "Add public key for users": "deploy/Setting up SSH keys.md"
  - Backend & Security:
    - "API notes": "backend/API.md"
    - "Keycloak (Auth)": "backend/Keycloak.md"
    - "OAuth / OIDC notes": "backend/OAuth _ OIDC dump.md"
    - "BIC node federation": "backend/BIC node federation.md"
  - Data model & Troubleshooting:
    - "Limitations of Neurobagel data model": "data/Limitations of Neurobagel data model.md"
    - "Troubleshooting HC_Diagnosis query results": "data/Troubleshooting erroneous HC_Diagnosis query results.md"


markdown_extensions:
  - admonition
  - pymdownx.magiclink
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences