name: Deploy the docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up cache for output
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Deploy
        run: |
          pip install -r requirements.txt 
          mkdocs gh-deploy --force